---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-copier
---
apiVersion: v1
kind: Pod
metadata:
  name: k8s-copier
spec:
  containers:
  - name: copier
    image: michaelfig/k8s-copier
    args:
    - --namespace=$(POD_NAMESPACE)
    - --target=federatedsecret,federatedhelmrelease
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
  serviceAccount: k8s-copier
