---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8s-copier
rules:
  - apiGroups: ["types.federation.k8s.io"]
    resources: ["federatedsecrets"]
    verbs: ["get","list","update","watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8s-copier-binding
subjects:
  - kind: ServiceAccount
    name: k8s-copier
    apiGroup: ""
roleRef:
  kind: Role
  name: k8s-copier
  apiGroup: ""
